project:
  type: website


title: "Asopinae of the World"
index: "main.html"

website:
  navbar:
    pinned: true
    background: info
    right:
      - href: index.qmd
        text: Home
      - href: distr_data.qmd
        text: Distribution map
      - href: raw.qmd
        text: Raw Data
      - href: bibliography.qmd
        text: Bibliography
      - href: collaborators.qmd
        text: Authors
     # - icon: github
      #  href: "https://github.com/afonsopoester"
      - text: "{{< iconify simple-icons researchgate >}}"
        href: "https://www.researchgate.net/profile/Joao-Afonso-Poester-Carvalho-2"
      - text: "{{< iconify academicons google-scholar-square >}}"
        href: "https://scholar.google.com.br/citations?user=O8awK9kAAAAJ&hl=pt-BR"
        
        
  page-footer: |
      This website was built using Quarto!
      
format:
  html:
    theme: 
      - cosmo
      - styles.scss



