project:
  type: website


title: "Asopinae of the World"

website:
  navbar:
    pinned: true
    background: info
    right:
      - href: main.qmd
        text: Home
      - href: distr_data.qmd
        text: Distribution map
      - href: raw.qmd
        text: Raw Data
      - href: bibliography.qmd
        text: Bibliography
      - href: collaborators.qmd
        text: Authors

        
        
  page-footer: |
      This website was built using Quarto!
      
format:
  html:
    theme: 
      - cosmo
      - styles.scss



